### ISSUE TITLE
Background color css attribute not support in html-pdf-node.

### ISSUE THREAD

**Issue by jacksonkasi1** [mrafiqk/html-pdf-node#102]
I face issue with `background-color` or `backround` css attribute.
it's dose not support when i convert html to pdf. 

here is  the demo web link. you can try out this: 
## [Demo website]( https://hml-to-pdf.onrender.com)

![image](https://github.com/mrafiqk/html-pdf-node/assets/109948871/519ba3cb-37ae-4d37-a36a-533f1830b84f)
![image](https://github.com/mrafiqk/html-pdf-node/assets/109948871/c3d92ca0-a0d3-42ec-873c-5bd044b8eff8)

how can i fix this issue?

**Comment by maiksicks** [comment]
@jacksonkasi1 I think you can solve it by adding [`print-color-adjust: exact;`](https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust) (or`-webkit-print-color-adjust: exact;`) to the `<body>`-tag of your html document. This will make backgrounds visible in prints.

**Comment by jacksonkasi1** [comment]
thanks @maiksicks 

`-webkit-print-color-adjust: exact;`

now it's work. 

![image](https://github.com/mrafiqk/html-pdf-node/assets/109948871/ffa9cb6d-2b08-4b77-87cd-acb81c7be2b9)
