### ISSUE TITLE
Custom fonts not applying on generated PDF file

### ISSUE THREAD

**Issue by mcama** [mrafiqk/html-pdf-node#5]
Hi!

I've got some local fonts and images served from an Express app that's running on localhost:5000.

I'm generating an HTML file to convert it to PDF, that has the CSS where I'm importing the previously mentioned fonts, using the following syntax:

```
@font-face {
    font-family: <font-name>;
    src: url('http://localhost:5000/fonts/<font-file-name>.otf');
}
```

My issue is that the fonts are not being applied to the text of the generated PDF file. On the other hand, all images (served by the same host) are correctly rendering in the generated PDF file.

I would appreciate if someone could point me in some direction to resolve this issue.

PS: I'm currenlty using `html-pdf-node v1.0.5` and `node v12.18.3`.

Thanks in advance.

**Comment by mcama** [comment]
As I supossed, this issue was caused by Chromium's CORS policiy, which was blocking font loading.

The issue resolves by passing the `--disable-web-security` arg to Puppeteer's browser. As there's no way to pass args to Puppeteer trought this plugin's API, I had to move to a custom Puppeteer implementation.

If anyone is facing this issue, you can pass the following args, directly to Puppeteer's browser:

```
const browser = await puppeteer.launch({
    args: ["--disable-web-security"],
    ...
});
```

I'm closing this issue, since it was not directly related to the plugin.

**Comment by JoseVov** [comment]
Something similar is happening to me too. But in my case all the fonts that I have installed on my computer are read correctly.

But if I use a Font that I don't have and reference it manually via path, it doesn't work.
