### ISSUE TITLE
Error: Protocol error (Page.printToPDF): Printing failed

### ISSUE THREAD

**Issue by smstahir** [mrafiqk/html-pdf-node#6]
I found the issue, it is related to chrome option i.e. headless and you did not implement/add this option
```
puppeteer.launch({
                    args: ["--no-sandbox", '--disable-setuid-sandbox'],
                    headless: true
                  });
```

**Comment by mrafiqk** [comment]
@smstahir Will implement and release it soon. Thanks for your information.

**Comment by mrafiqk** [comment]
@smstahir I have added arguments support. This options will overwrite the default arguments.
The default arguments are `['--no-sandbox', '--disable-setuid-sandbox']`.

**Example:-**
```js
let options = { format: 'A4', args: ['--no-sandbox', '--disable-setuid-sandbox'] };
let file = { content: "<h1>Welcome to html-pdf-node</h1>" };
// or //
let file = { url: "https://example.com" };
html_to_pdf.generatePdf(file, options).then(pdfBuffer => {
  console.log("PDF Buffer:-", pdfBuffer);
});
```

**Comment by mrafiqk** [comment]
@smstahir I am closing this issue. If you are facing the same problem again, you can re-open this issue anytime.

Thanks
