### ISSUE TITLE
PDF file does not generate on live server. Works in dev.

### ISSUE THREAD

**Issue by MaksemM** [mrafiqk/html-pdf-node#63]
I'm not sure what is happening here:

```
html_to_pdf.generatePdf(file, options).then(pdfBuffer => {
                console.log("PDF Buffer:-", pdfBuffer)
            })
```

This works in dev and the file is generated correctly into the correct file path. 

However it does not work on the live server. Any suggestions please?

**Comment by MaksemM** [comment]
This line actually creates the file in the correct directory on the live server and dev server:

`fs.writeFileSync(path + filename, htmlContent)`

Still can't figure out why the code in the first comment doesn't work on live server?

I have tested paths and it is not the path name. It has something to do with the actual generation of the PDF by the looks of it.

**Comment by MaksemM** [comment]
So I solved this issue by not using this package and using html-pdf instead. Worked straight out of the box. I would recommend others do the same if they experience these issues.

**Comment by Siddharth2212** [comment]
LALALALAND this issue is closed without even solving
