### ISSUE TITLE
Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.

### ISSUE THREAD

**Issue by marafee1243** [mrafiqk/html-pdf-node#9]
```
2020-12-15T09:43:12.292Z        d03d2294-4316-1e4d-5ae2-0e8201298173    ERROR   Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)
    at async Object.generatePdf (/var/task/node_modules/html-pdf-node/index.js:17:19)
    at async create (/var/task/http/controllers/pdf/PdfController.js:92:22)
    at async /var/task/routes/index.js:59:3
```

Got this error when trying to run on AWS EC2. (also tried on aws sam cli)

I tried installing `PUPPETEER_PRODUCT=firefox npm install` but still the same

**Comment by mrafiqk** [comment]
@marafee1243 
Only that you somehow have to install `google chrome` with apt-get in Ubuntu and create an environment variable 
 `PUPPETEER_EXECUTABLE_PATH='/usr/bin/google-chrome'`

**Comment by TrejoCode** [comment]
> @marafee1243
> Only that you somehow have to install `google chrome` with apt-get in Ubuntu and create an environment variable
> `PUPPETEER_EXECUTABLE_PATH='/usr/bin/google-chrome'`

Your project is great, but, if it's necessary, update the README for this issue.
Thanks.

**Comment by mrafiqk** [comment]
@marafee1243 @TrejoCode Could you please confirm the above solution is worked or not?

**Comment by TrejoCode** [comment]
> @marafee1243 @TrejoCode Could you please confirm the above solution is worked or not?

Not for me, because i'm on Windows, but let check in my Ubuntu VPS

**Comment by marafee1243** [comment]
@mrafiqk My apologies, I totally lost on this. I was using AWS EC2 with AWS linux. Havent tried it. I think i will close this issue.

**Comment by ostwalprasad** [comment]
I was 

> @marafee1243
> Only that you somehow have to install `google chrome` with apt-get in Ubuntu and create an environment variable
> `PUPPETEER_EXECUTABLE_PATH='/usr/bin/google-chrome'`

This works. Tested on `node:14.16.0-buster-slim` Docker image. Thanks

**Comment by marvincorreia** [comment]
For node:alpine docker image use this following Dockerfile config:

```
FROM node:16.13.2-alpine
...
RUN apk add chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
...
```

**Comment by vinideep** [comment]
i got the same error in vercel logs
